language: node_js
node_js:
- '10'
env:
  global:
  - IMAGE_NAME=luckjs/danielkarski
  - CONTAINER_NAME=danielkarski_master
  - VIRTUAL_HOST=danielkarski.pl
jobs:
  include:
  - stage: build
    services:
      - docker
    script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - TRACKING_ID=$TRACKING_ID yarn install && yarn build
      - mv public server/
      - docker build --pull -t $IMAGE_NAME server/
      - docker push $IMAGE_NAME
    if: branch = master

  - stage: deploy
    before_deploy:
      - openssl aes-256-cbc -K $encrypted_45457958fdd0_key -iv $encrypted_45457958fdd0_iv
        -in .travis/id_rsa.enc -out .travis/id_rsa -d
      - eval "$(ssh-agent -s)"
      - cp .travis/id_rsa ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-add ~/.ssh/id_rsa
      - chmod 700 ~/.ssh
      - ssh-keyscan $HOST_IP > ~/.ssh/known_hosts
    script: skip
    if: branch = master
    env:
      - IMAGE_NAME=$IMAGE_NAME
      - CONTAINER_NAME=$CONTAINER_NAME
      - VIRTUAL_HOST=$VIRTUAL_HOST
    deploy:
      - provider: script
        skip_cleanup: true
        script: bash .travis/deploy.sh $HOST_IP $DOCKER_PASSWORD $DOCKER_USERNAME $IMAGE_NAME $CONTAINER_NAME
        on:
          branch: master

